version: '3'
services:
    nullchan:
        build: .
    nullchan-frontend:
        build: ./frontend
        hostname: nullchan-frontend
    minio:
        image: "minio/minio"
        hostname: minio
        restart: always
        depends_on:
            - dnsproxy
        environment:
            - MINIO_ACCESS_KEY=minio
            - MINIO_SECRET_KEY=miniostorage
        volumes:
            - compose-minio:/data
        command: server /data
    nginx:
        image: nginx
        restart: always
        ports:
            - "5000:5000"
        depends_on:
            - nullchan
        volumes:
            - ./deploy-configs/nginx.conf:/etc/nginx/nginx.conf
    postgres:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=dev
            - POSTGRES_PASSWORD=dev
            - POSTGRES_DB=dev
        volumes:
            - compose-postgres:/var/lib/postgresql/data
    redis:
        image: redis
        hostname: redis
        restart: always
        command: [sh, -c, "rm -f /data/dump.rdb && redis-server --save ''"]
    dnsproxy:
        image: "defreitas/dns-proxy-server"
        hostname: "dns.mageddo"
        network_mode: host
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /etc/resolv.conf:/etc/resolv.conf
volumes:
  compose-minio:
  compose-postgres:
